#!/usr/bin/env sh

PWR='/sys/class/power_supply'
SEP=${SEP:-', '}
BATS=$@
LINE=''

for BAT in $BATS; do
  SYSFS="${PWR}/${BAT}"
  if [ -d "$SYSFS" ]; then
    CHARGE=$(cat "${SYSFS}/capacity")
    STATUS=$(cat "${SYSFS}/status" | tr '[:lower:]' '[:upper:]')
    STATUS="${STATUS:0:3}"
    LINE="${LINE}${LINE:+$SEP}${BAT}: ${STATUS} ${CHARGE}%"
  fi
done

[ "${LINE}" != '' ] && echo $LINE
