#!/bin/sh

PWR='/sys/class/power_supply'
FMT=${FMT:-'${BAT}: ${STATUS} ${CHARGE}%'}
SEP=${SEP:-', '}
BATS=$@
LINE=''

for BAT in $BATS; do
  SYSFS="${PWR}/${BAT}"
  if [ -d "$SYSFS" ]; then
    export BAT
    export CHARGE=$(cat "${SYSFS}/capacity")

    STATUS=$(cat "${SYSFS}/status" | tr '[:lower:]' '[:upper:]')
    export STATUS="${STATUS:0:3}"

    LINE=${LINE}${LINE:+$SEP}$(echo "$FMT" | envsubst '${BAT}${STATUS}${CHARGE}')
  fi
done

[ "${LINE}" != '' ] && echo $LINE
