#!/usr/bin/env sh

{
  pkill wireplumber
  pkill pipewire-pulse
  pkill pipewire
  sleep 1
  pipewire &
  sleep 1
  pipewire-pulse &
  wireplumber &
  pipewire -c "${XDG_CONFIG_HOME}/pipewire/filter-chain/rnnoise.conf"
} >/dev/null 2>&1 &
