#!/usr/bin/env sh

[ -z $XDG_RUNTIME_DIR ] && {
  UID=$(id -u)
  GID=$(id -g)
  XDG_RUNTIME_DIR=/run/user/${UID}

  [ -d ${XDG_RUNTIME_DIR} ] || {
    doas mkdir -p ${XDG_RUNTIME_DIR}
    doas chown ${UID}:${GID} ${XDG_RUNTIME_DIR}
  }
}

echo ${XDG_RUNTIME_DIR}
