export EDITOR="emacsclient -a \"\" -c"
export VISUAL="$EDITOR -n"
export TERMINAL="$VISUAL -e '(eshell t)'"
export QTERM="$VISUAL -e '(eshell)'"
export BROWSER="firefox-wayland"
export GRIM_DEFAULT_DIR="$HOME/pics/screen/"
