#!/usr/bin/env sh

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Pretend we're GNOME to piggyback theme settings
export XDG_CURRENT_DESKTOP="GNOME"

# Nice cursor
export XCURSOR_THEME="Adwaita"

# Disable access control for the current user.
xhost +SI:localuser:$USER

# Set default cursor.
xsetroot -cursor_name left_ptr

# Xsettings
xsettingsd &

# Compositing
picom &

# Audio
pipewire &

# Start window manager
STARTX=${USERXSESSION:-$HOME/.xsession}
eval "$STARTX"
