#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Discord desktop='^6'

pkill -SIGUSR1 sxhkd
