#!/bin/bash

OUTPUTS=($(xrandr | grep '\sconnected' | cut -d ' ' -f 1))
NUM_OUTPUTS=${#OUTPUTS[@]}

NUM_DESKTOPS=9
PER_DESKTOP=$(((NUM_DESKTOPS / NUM_OUTPUTS) - 1))
DESK=1

pkill polybar

for output in $OUTPUTS; do
  bspc monitor $output -d $(seq $DESK $((DESK + PER_DESKTOP)))
  DESK=$((DESK + PER_DESKTOP))
  MONITOR=$output polybar --reload default &
done

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a discord desktop='^6'
bspc rule -a Zathura state=tiled

pkill -SIGUSR1 sxhkd
